FROM node:20-alpine

# Enable pnpm via corepack
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Copy only lockfile first for better caching
COPY package-lock.json package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

EXPOSE 5173

CMD ["npm","run","dev","--host","0.0.0.0"]
