services:
  api-ims:
    image: ims:${TAG-latest}
    labels:
      - traefik.enable=true
      - traefik.docker.network=dev-net
      - traefik.http.services.ims-backend.loadbalancer.server.port=8000
      - traefik.http.routers.ims-backend.rule=Host(`api-ims.localhost`)
      - traefik.http.routers.ims-backend.entrypoints=http
    networks:
      - dev-net
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:password@postgres:5432/ims
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]
    # develop:
    #   watch:
    #     - path: .
    #       action: sync
    #       target: /app
    #       ignore:
    #         - .venv
    #     - path: ./pyproject.toml
    #       action: rebuild
    volumes:
      - ./:/app
      - /app/.venv

networks:
  dev-net:
    external: true