"""add_unit_price

Revision ID: 38f21f7b0502
Revises: 0001_initial
Create Date: 2026-08-24 08:02:06.936477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38f21f7b0502"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saleitem",
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.execute(
        """
        UPDATE saleitem
        SET unit_price = amount / NULLIF(quantity, 0)
        WHERE unit_price IS NULL
        """
    )

    op.alter_column(
        "saleitem",
        "unit_price",
        existing_type=sa.Numeric(12, 2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("saleitem", "unit_price")
    # ### end Alembic commands ###
